/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_longbridge_SdkNative */

#ifndef _Included_com_longbridge_SdkNative
#define _Included_com_longbridge_SdkNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_longbridge_SdkNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_init
  (JNIEnv *, jclass);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    newConfig
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_longbridge_SdkNative_newConfig
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    newConfigFromEnv
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_longbridge_SdkNative_newConfigFromEnv
  (JNIEnv *, jclass);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    freeConfig
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_freeConfig
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    newQuoteContext
 * Signature: (JLcom/longbridge/quote/QuotePushHandler;Lcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_newQuoteContext
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    freeQuoteContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_freeQuoteContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextSubscribe
 * Signature: (J[Ljava/lang/String;IZLcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextSubscribe
  (JNIEnv *, jclass, jlong, jobjectArray, jint, jboolean, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextUnsubscribe
 * Signature: (J[Ljava/lang/String;ILcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextUnsubscribe
  (JNIEnv *, jclass, jlong, jobjectArray, jint, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextSubscriptions
 * Signature: (JLcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextSubscriptions
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextStaticInfo
 * Signature: (J[Ljava/lang/String;Lcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextStaticInfo
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextQuote
 * Signature: (J[Ljava/lang/String;Lcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextQuote
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextOptionQuote
 * Signature: (J[Ljava/lang/String;Lcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextOptionQuote
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextWarrantQuote
 * Signature: (J[Ljava/lang/String;Lcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextWarrantQuote
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextDepth
 * Signature: (JLjava/lang/String;Lcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextDepth
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextBrokers
 * Signature: (JLjava/lang/String;Lcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextBrokers
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextParticipants
 * Signature: (JLcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextParticipants
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longbridge_SdkNative
 * Method:    quoteContextTrades
 * Signature: (JLjava/lang/String;ILcom/longbridge/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longbridge_SdkNative_quoteContextTrades
  (JNIEnv *, jclass, jlong, jstring, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
