package com.longport.quote;

public enum WarrantSortBy {
    LastDone,
    ChangeRate,
    ChangeValue,
    Volume,
    Turnover,
    ExpiryDate,
    StrikePrice,
    UpperStrikePrice,
    LowerStrikePrice,
    OutstandingQuantity,
    OutstandingRatio,
    Premium,
    ItmOtm,
    ImpliedVolatility,
    Delta,
    CallPrice,
    ToCallPrice,
    EffectiveLeverage,
    LeverageRatio,
    ConversionRatio,
    BalancePoint,
    Status,
}
