package com.longbridge.quote;

public enum SecurityBoard {
    Unknown,
    USMain,
    USPink,
    USDJI,
    USNSDQ,
    USSector,
    USOption,
    USOptionS,
    HKEquity,
    HKPreIPO,
    HKWarrant,
    HKHS,
    HKSector,
    SHMainConnect,
    SHMainNonConnect,
    SHSTAR,
    CNIX,
    CNSector,
    SZMainConnect,
    SZMainNonConnect,
    SZGEMConnect,
    SZGEMNonConnect,
    SGMain,
    STI,
    SGSector,
}
